theme: jekyll-theme-midnight
title: Práctica 11 - Cliente y servidor para una aplicación de procesamiento de notas de texto
author: Marcos Padilla Herrera
description: Aplicación de procesamiento de notas de texto.
